import Providers from '@/contexts/Providers';
import { opensans } from '@/lib/fonts';
import type { Metadata } from 'next';
import { Toaster } from 'react-hot-toast';
import './globals.css';

export const metadata: Metadata = {
  title: {
    template: '%s : Pria',
    default: 'Pria | Ecommerce app',
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${opensans.className} flex min-h-screen flex-col text-sm text-gray-custom-1 antialiased`}
      >
        <Providers>{children}</Providers>
        <Toaster
          position="top-right"
          gutter={12}
          toastOptions={{
            success: {
              duration: 3000,
            },
            error: {
              duration: 5000,
            },
            style: {
              fontSize: '12px',
              maxWidth: '500px',
              padding: '6px 9px',
              backgroundColor: 'white',
              color: '#353535',
            },
          }}
        />
      </body>
    </html>
  );
}
